version: '3.8'

services:
  web_server:
    build:
      context: ./web_server
      dockerfile: Dockerfile
    image: ece1779-local/web-monitoring:latest
    ports:
      - "5001:5000"
    networks:
      - monitoring
    expose:
      - "5000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.rules.yml:/etc/prometheus/alert.rules.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
