global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "web_server"
    static_configs:
      - targets: ["web_server:5000"]
    metrics_path: /metrics
rule_files:
  - /etc/prometheus/alerts.rules.yml

